repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-added-large-files
        args: [--maxkb=2048]
    -   id: check-symlinks
    -   id: check-vcs-permalinks
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: fix-byte-order-marker
    -   id: check-toml
