title = '.sh'
description = 'Tech blog run by Seokjin Han'
base_url = 'https://blog.raifthenerd.com'
default_language = 'en'

compile_sass = true
minify_html = true

generate_feed = true
build_search_index = false

ignored_content = []

[markdown]
highlight_code = true
highlight_theme = 'css'
highlight_themes_css = [
  { theme = 'solarized-light', filename = 'css/syntax.css' },
]
smart_punctuation = true
render_emoji = true

[extra]
author = 'Seokjin Han'
github = 'raifthenerd'
google_analytics = 'G-XXY96K3XP3'
google_adsense = 'ca-pub-5141260618801038'
